#!/bin/bash
# Quick reference for the autonomous agent

echo "🤖 Autonomous Agent - Quick Reference"
echo "======================================"
echo ""
echo "The agent now handles EVERYTHING automatically!"
echo ""
echo "Your Devices:"
adb devices
echo ""
echo "Usage:"
echo "------"
echo ""
echo "1. Fix a GitHub issue (fully automated):"
echo "   ./scripts/start-agent.sh <issue_number>"
echo ""
echo "   Example:"
echo "   ./scripts/start-agent.sh 42"
echo ""
echo "   What happens automatically:"
echo "   ✅ Detects devices"
echo "   ✅ Auto-selects device (prefers emulator)"
echo "   ✅ Fetches issue from GitHub"
echo "   ✅ Implements fix"
echo "   ✅ Builds project"
echo "   ✅ Runs unit tests"
echo "   ✅ Installs on device"
echo "   ✅ Runs instrumented tests"
echo "   ✅ Checks for crashes"
echo "   ✅ Creates Pull Request"
echo ""
echo "2. Complete workflow with details:"
echo "   ./scripts/complete-workflow.sh <issue_number>"
echo ""
echo "3. Quick app testing:"
echo "   ./run-app.sh"
echo ""
echo "4. Manual validation:"
echo "   ./pre-push-validation.sh"
echo ""
echo "Current Branch:"
git branch --show-current
echo ""
echo "Documentation:"
echo "  - FULLY_AUTONOMOUS_AGENT.md - Complete guide"
echo "  - AUTOMATION_IMPLEMENTATION.md - Implementation details"
echo "  - AUTOMATION_GUIDE.md - User guide"
echo ""
echo "✨ The agent is fully autonomous - just provide an issue number!"

