#!/bin/bash

# Create Pull Request Script
# Usage: ./create-pr.sh <branch_name> <issue_number> <pr_title>

set -e

BRANCH_NAME=$1
ISSUE_NUMBER=$2
PR_TITLE=$3
BASE_BRANCH=${4:-main}

if [ -z "$BRANCH_NAME" ] || [ -z "$ISSUE_NUMBER" ]; then
    echo "❌ Error: Missing required arguments"
    echo "Usage: ./create-pr.sh <branch_name> <issue_number> <pr_title> [base_branch]"
    exit 1
fi

if [ -z "$PR_TITLE" ]; then
    PR_TITLE="Fix: Issue #${ISSUE_NUMBER}"
fi

echo "🚀 Creating Pull Request..."
echo "  Branch: ${BRANCH_NAME}"
echo "  Issue: #${ISSUE_NUMBER}"
echo "  Title: ${PR_TITLE}"
echo "  Base: ${BASE_BRANCH}"
echo ""

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI (gh) not installed"
    echo "Install: brew install gh"
    exit 1
fi

# Generate PR body
PR_BODY=$(cat <<EOF
## 🤖 Automated Fix for Issue #${ISSUE_NUMBER}

### 📋 Issue Details
This PR addresses issue #${ISSUE_NUMBER}

### 🔧 Changes Made
- Automated fixes applied by CI/CD agent
- All tests passing
- Code coverage maintained

### ✅ Testing
- [x] Unit tests passed
- [x] Code coverage checked
- [x] Build successful

### 📊 Test Reports
Test reports and coverage data are available in the CI artifacts.

### 🔍 Review Checklist
- [ ] Code changes reviewed
- [ ] Tests are comprehensive
- [ ] Documentation updated if needed
- [ ] No breaking changes introduced

---
**Generated by**: Automated CI/CD Agent
**Timestamp**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

Closes #${ISSUE_NUMBER}
EOF
)

# Create PR as draft
echo "📝 Creating draft pull request..."
gh pr create \
    --title "$PR_TITLE" \
    --body "$PR_BODY" \
    --base "$BASE_BRANCH" \
    --head "$BRANCH_NAME" \
    --label "automated,needs-review" \
    --draft

PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number -q '.[0].number')

echo ""
echo "✅ Pull Request created successfully!"
echo "  PR Number: #${PR_NUMBER}"
echo "  URL: $(gh pr view $PR_NUMBER --json url -q .url)"
echo ""
echo "📌 Next Steps:"
echo "  1. Review the automated changes"
echo "  2. Check test reports in CI artifacts"
echo "  3. Mark PR as ready for review"
echo "  4. Request reviews from team members"
echo ""

# Comment on the original issue
echo "💬 Linking PR to issue..."
gh issue comment $ISSUE_NUMBER --body "🤖 Automated fix in progress: PR #${PR_NUMBER}

[View Pull Request]($(gh pr view $PR_NUMBER --json url -q .url))"

echo "✨ Done! PR is ready for review."

